### ISSUE TITLE
WARNING: cannot use rsync: rsync not available in container

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/e2e-benchmarking#239]
When running the router v2 test with comparisons enabled there is a warning presented after all the tests are running stating that rysnc is not available in the container. It is unclear if this is actually a problem or not.

example error:
```
Indexing documents in router-test-results
10-09-2021T18:07:55 Sleeping for 6s before next test
10-09-2021T18:08:01 Enabling cluster version and ingress operators
deployment.apps/cluster-version-operator scaled
deployment.apps/ingress-operator scaled
WARNING: cannot use rsync: rsync not available in container
results.csv
10-09-2021T18:08:05 delete tuned profile for node labeled with node-role.kubernetes.io/workload 
tuned.tuned.openshift.io "openshift-ingress-performance" deleted
10-09-2021T18:08:06 Deleting infrastructure
```

**Comment by rsevilla87** [comment]
The error comes from this statement
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/d7d83d34f91c7604e6cc59310cc8cd634ad4e0e7/workloads/router-perf-v2/ingress-performance.sh#L31

This is "expected", as the rsync command is not available in the mb container, however it doesn't hang because it falls back to `tar` when rsync is not available. We can fix it by replacing it by `oc cp` which directly uses tar

**Comment by Harshith-umesh** [comment]
closing this issue since it's only a warning and not an error. rsync falls back to using tar in case rsync is not installed on the container.
