### ISSUE TITLE
router-perf: update default CLIENTS after maxconn changed from 20k to 50k in 4.12

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/e2e-benchmarking#519]
Connection Capacity for default 2 routers
`number of router(default 2) x default maxConnections(50k) = 100k connections`
Culculation for proper CLIENT
small scale(100 routes)
For http and passthrough, number of routes(100 for large scale) x clients(1000) = 100k. 
For edge and re-encrypt, number of routes(100 for large scale) x clients(500)x2 = 100k
To leave some buffer, 400 is a good number for SMALL_SCALE_CLIENTS

For mix termination, number of routes(100) x 2 (http and passthrough) x clients(150) + routes(100) x 2(edge and re-encrypt) x 2(connection per termination) x clients(150) =90k connections
150 is a good number for SMALL_SCALE_CLIENTS_MIX

large scale(500 routes)
For http and passthrough, number of routes(500 for large scale) x clients(200) = 100k
For edge and re-encrypt, number of routes(500 for large scale) x clients(100)x2 = 100k
To leave some buffer, 80 is a good number for LARGE_SCALE_CLIENTS

For mix termination, number of routes(500) x 2 (http and passthrough) x clients(30) + routes(500) x 2(edge and re-encrypt) x 2(connection per termination) x clients(30) =90k connections
30 is a good number for LARGE_SCALE_CLIENTS_MIX

Proposal:
```
SMALL_SCALE_CLIENTS 1 40 200-> 1 200 400
SMALL_SCALE_CLIENTS_MIX 1 20 80 -> 1 50 150
LARGE_SCALE_CLIENTS 1 20 80-> 1 40 80
LARGE_SCALE_CLIENTS_MIX 1 10 20-> 1 10 30
```

@rsevilla87 Please let me know your comments. I will open a PR when we get an agreement.

**Comment by rsevilla87** [comment]
I like this proposal @qiliRedHat, however it comes with some caveats since maxConnections=50K is defaulted in 4.12 as you suggested in the title.

If I've understood correctly, the maximum connections created by each test should be :

Edge & passthrough = routes * clients * 2 (edge & passthrough) 
Mix =  routes * clients * 1.5 (half of the routes are edge & passthrough) 


- Small scale -> 100x400x2=80K
- Small scale mix -> 400x150x1.5=90K   <--- Leaving only 10K connections as buffer could be dangerous, I propose using 125 clients  to reach 75K connections

- Large scale -> 500x80x2=80K
- Large scale mix -> 2000x30x1.5=90K  <--- Leaving only 10K connections as buffer could be dangerous, I propose using 25 clients to reach 75K connections


Where each router supports up to 50K connections, we deploy 2 routers by default. Hence they can handle up to 100K connections.

Other than that, I'd remove some of the iterations to make this test a bit shorter as proposed already at https://github.com/cloud-bulldozer/e2e-benchmarking/pull/452

```
SMALL_SCALE_CLIENTS 1 40 200-> 1 400
SMALL_SCALE_CLIENTS_MIX 1 20 80 -> 1 125
LARGE_SCALE_CLIENTS 1 20 80-> 1 80
LARGE_SCALE_CLIENTS_MIX 1 10 20-> 1 25
```

**Comment by qiliRedHat** [comment]
I made the change in PR https://github.com/cloud-bulldozer/e2e-benchmarking/pull/518/files

**Comment by rsevilla87** [comment]
Fixed in https://github.com/cloud-bulldozer/e2e-benchmarking/issues/519
